# Generated by Django 5.2.8 on 2025-11-12 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='📚', help_text='Emoji icon (e.g., 📚, 📖, 💻)', max_length=10)),
                ('title', models.CharField(help_text='Slide title', max_length=255)),
                ('description', models.TextField(help_text='Slide description')),
                ('router_id', models.CharField(blank=True, help_text='Router ID for specific device (blank = all routers)', max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers shown first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slide Content',
                'verbose_name_plural': 'Slide Contents',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
