# Generated by Django 5.2.8 on 2025-11-13 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_slidecontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='📚', help_text='Emoji icon (e.g., 📚, 💻, 🎓)', max_length=10)),
                ('title', models.CharField(help_text='Card title', max_length=255)),
                ('description', models.TextField(help_text='Card description')),
                ('router_id', models.CharField(blank=True, help_text='Router ID (blank = all routers)', max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers shown first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this card')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Content',
                'verbose_name_plural': 'Card Contents',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Template name for identification', max_length=255)),
                ('left_panel_component', models.CharField(choices=[('slideshow', 'Slideshow (Icons + Text + Dots)'), ('fullbg', 'Full Background (No Text Overlay)'), ('cardgallery', 'Card Gallery (Grid of Cards)')], default='slideshow', help_text='Component type for left panel', max_length=50)),
                ('router_id', models.CharField(blank=True, help_text='Router ID (blank = all routers)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Set as active template for this router')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Configuration',
                'verbose_name_plural': 'Template Configurations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
