# Generated by Django 5.2.8 on 2025-11-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cardcontent_templateconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcontent',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Icon image file (recommended size: 100x100px)', null=True, upload_to='card_icons/'),
        ),
        migrations.AddField(
            model_name='slidecontent',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Icon image file (recommended size: 100x100px)', null=True, upload_to='slide_icons/'),
        ),
        migrations.AlterField(
            model_name='cardcontent',
            name='icon',
            field=models.CharField(blank=True, default='📚', help_text='Emoji icon (e.g., 📚, 💻, 🎓) - optional if using image', max_length=10),
        ),
        migrations.AlterField(
            model_name='slidecontent',
            name='icon',
            field=models.CharField(blank=True, default='📚', help_text='Emoji icon (e.g., 📚, 📖, 💻) - optional if using image', max_length=10),
        ),
    ]
