# Generated by Django 4.2.11 on 2025-11-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cardcontent_icon_image_slidecontent_icon_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundimage',
            old_name='router_id',
            new_name='hotspot_name',
        ),
        migrations.RenameField(
            model_name='cardcontent',
            old_name='router_id',
            new_name='hotspot_name',
        ),
        migrations.RenameField(
            model_name='slidecontent',
            old_name='router_id',
            new_name='hotspot_name',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='default_router_id',
            new_name='default_hotspot_name',
        ),
        migrations.RenameField(
            model_name='templateconfig',
            old_name='router_id',
            new_name='hotspot_name',
        ),
        migrations.AlterField(
            model_name='templateconfig',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Set as active template for this hotspot'),
        ),
    ]
