# Generated by Django 4.2.11 on 2025-11-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_router_id_to_hotspot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='hotspot_name',
            field=models.CharField(blank=True, help_text="Hotspot name (e.g., 'hotspot', 'hotspot_lib') - blank for all hotspots", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardcontent',
            name='hotspot_name',
            field=models.CharField(blank=True, help_text="Hotspot name (e.g., 'hotspot', 'hotspot_lib') - blank for all hotspots", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slidecontent',
            name='hotspot_name',
            field=models.CharField(blank=True, help_text="Hotspot name (e.g., 'hotspot', 'hotspot_lib') - blank for all hotspots", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='default_hotspot_name',
            field=models.CharField(blank=True, help_text='Default hotspot name', max_length=100),
        ),
        migrations.AlterField(
            model_name='templateconfig',
            name='hotspot_name',
            field=models.CharField(blank=True, help_text="Hotspot name (e.g., 'hotspot', 'hotspot_lib') - blank for all hotspots", max_length=100, null=True),
        ),
    ]
