# Generated by Django 4.2.11 on 2025-11-17 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_backgroundimage_hotspot_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='hotspot_status_refresh_interval',
            field=models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '60 minutes')], default=10, help_text='Auto-refresh interval for hotspot status (in minutes)'),
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_name', models.CharField(help_text="Technical hotspot name (e.g., 'hotspot', 'hotspot_lab', 'hotspot_office')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Friendly display name (e.g., 'Default Hotspot', 'Laboratory')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of this hotspot location/purpose')),
                ('is_active', models.BooleanField(default=True, help_text='Is this hotspot currently in use?')),
                ('folder_exists', models.BooleanField(default=False, help_text='Does the hotspot_xxx folder exist?')),
                ('login_file_exists', models.BooleanField(default=False, help_text='Does login.html file exist in the folder?')),
                ('config_matched', models.BooleanField(default=False, help_text='Does window.HOTSPOT_NAME match the hotspot_name?')),
                ('last_checked', models.DateTimeField(blank=True, help_text='Last time connection was tested', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hotspots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotspot',
                'verbose_name_plural': 'Hotspots',
                'ordering': ['hotspot_name'],
            },
        ),
    ]
