# Generated by Django 4.2.11 on 2025-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_systemsettings_hotspot_status_refresh_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_name', models.CharField(db_index=True, help_text='Hotspot identifier', max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When page was viewed')),
                ('mac_hash', models.CharField(db_index=True, help_text='SHA256 hash of MAC address', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address assigned', null=True)),
                ('device_type', models.CharField(blank=True, help_text='mobile/desktop/tablet', max_length=20, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('time_on_page', models.IntegerField(blank=True, help_text='Seconds spent on page', null=True)),
                ('is_unique_today', models.BooleanField(default=True, help_text='First impression from this device today')),
            ],
            options={
                'verbose_name': 'Page Impression',
                'verbose_name_plural': 'Page Impressions',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['hotspot_name', 'viewed_at'], name='api_pageimp_hotspot_0212d3_idx'), models.Index(fields=['mac_hash', 'viewed_at'], name='api_pageimp_mac_has_98e7fd_idx'), models.Index(fields=['hotspot_name', 'mac_hash', 'viewed_at'], name='api_pageimp_hotspot_83a26b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyReachStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_name', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('total_impressions', models.IntegerField(default=0, help_text='Total page views')),
                ('unique_devices', models.IntegerField(default=0, help_text='Unique MAC addresses')),
                ('mobile_count', models.IntegerField(default=0)),
                ('desktop_count', models.IntegerField(default=0)),
                ('tablet_count', models.IntegerField(default=0)),
                ('unknown_count', models.IntegerField(default=0)),
                ('avg_time_on_page', models.FloatField(default=0.0, help_text='Average seconds on page')),
                ('total_time_on_page', models.IntegerField(default=0, help_text='Total seconds across all impressions')),
                ('hourly_data', models.JSONField(blank=True, default=dict, help_text='Hourly impression counts {hour: count}', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Reach Statistics',
                'verbose_name_plural': 'Daily Reach Statistics',
                'ordering': ['-date', 'hotspot_name'],
                'indexes': [models.Index(fields=['date', 'hotspot_name'], name='api_dailyre_date_f8877f_idx'), models.Index(fields=['hotspot_name', 'date'], name='api_dailyre_hotspot_8a8a5a_idx')],
                'unique_together': {('hotspot_name', 'date')},
            },
        ),
    ]
