# Generated by Django 4.2.11 on 2025-11-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_page_impression_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Organization name (e.g., University, Library)', max_length=255),
        ),
    ]
