# Generated by Django 4.2.11 on 2025-11-18 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_add_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Description (e.g., Library Portal, Promotion Page)', max_length=255)),
                ('url', models.URLField(help_text='Redirect URL after successful login', max_length=500)),
                ('hotspot_name', models.CharField(db_index=True, help_text='Hotspot identifier', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Active redirect for this hotspot')),
                ('redirect_count', models.IntegerField(default=0, help_text='Number of times users were redirected')),
                ('last_redirected_at', models.DateTimeField(blank=True, help_text='Last redirect timestamp', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Priority (higher = preferred if multiple active)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing Page URL',
                'verbose_name_plural': 'Landing Page URLs',
                'ordering': ['-is_active', '-priority', '-created_at'],
                'indexes': [models.Index(fields=['hotspot_name', 'is_active'], name='api_landing_hotspot_d446c7_idx'), models.Index(fields=['is_active', 'hotspot_name'], name='api_landing_is_acti_a153ab_idx')],
            },
        ),
    ]
