# Generated by Django 4.2.11 on 2025-11-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_landing_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidecontent',
            name='image_size',
            field=models.CharField(choices=[('square_600', '600x600 (Square Large)'), ('square_400', '400x400 (Square Medium)'), ('square_200', '200x200 (Square Small)'), ('landscape_600', '600x450 (4:3 Large)'), ('landscape_400', '400x300 (4:3 Medium)'), ('landscape_200', '200x150 (4:3 Small)')], default='square_400', help_text='Image display size (only applies when using icon_image)', max_length=20),
        ),
        migrations.AddField(
            model_name='slidecontent',
            name='link_text',
            field=models.CharField(blank=True, default='อ่านต่อ', help_text='Button text (max 50 characters)', max_length=50),
        ),
        migrations.AddField(
            model_name='slidecontent',
            name='link_url',
            field=models.URLField(blank=True, help_text='Link URL (e.g., https://example.com)', null=True),
        ),
        migrations.AddField(
            model_name='slidecontent',
            name='show_description',
            field=models.BooleanField(default=True, help_text='Show/hide slide description'),
        ),
        migrations.AddField(
            model_name='slidecontent',
            name='show_link',
            field=models.BooleanField(default=False, help_text='Show call-to-action button with link'),
        ),
        migrations.AddField(
            model_name='slidecontent',
            name='show_title',
            field=models.BooleanField(default=True, help_text='Show/hide slide title'),
        ),
    ]
