# Generated by Django 5.2.8 on 2026-02-27 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_slidecontent_image_size_slidecontent_link_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อหน่วยงาน (e.g., คณะวิทยาศาสตร์, สำนักหอสมุด)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='รายละเอียดหน่วยงาน')),
                ('is_active', models.BooleanField(default=True, help_text='หน่วยงานนี้ยังใช้งานอยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
                ('hotspots', models.ManyToManyField(blank=True, help_text='Hotspot ที่หน่วยงานนี้สามารถเข้าถึงได้', related_name='departments', to='api.hotspot')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
    ]
