# Generated by Django 5.2.8 on 2026-04-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_department_add_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='has_active_background',
            field=models.BooleanField(default=False, help_text='Does this hotspot have an active BackgroundImage (own or default)?'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='has_active_template',
            field=models.BooleanField(default=False, help_text='Does this hotspot have an active TemplateConfig (own or default)?'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='has_landing_url',
            field=models.BooleanField(default=False, help_text='Does this hotspot have a LandingPageURL configured (own or default)?'),
        ),
    ]
